
(()=>{'use strict';
 const slides=[...document.querySelectorAll('.slide')], $=id=>document.getElementById(id);
 let current=0,reading=innerWidth<800; const timers=[];
 function scale(){document.documentElement.style.setProperty('--scale',String(Math.min(innerWidth/1280,(innerHeight-72)/720)));}
 function pauseTimers(){timers.forEach(t=>t.pause());}
 function show(index,scroll=true){current=Math.max(0,Math.min(slides.length-1,Number(index)||0));pauseTimers();slides.forEach((s,i)=>{s.classList.toggle('active',i===current);if(!reading)s.setAttribute('aria-hidden',String(i!==current));else s.removeAttribute('aria-hidden');});$('counter').textContent=String(current+1).padStart(2,'0')+' / '+slides.length;$('prev-btn').disabled=current===0;$('next-btn').disabled=current===slides.length-1;history.replaceState(null,'','#s'+String(current+1).padStart(2,'0'));if(reading&&scroll)slides[current].scrollIntoView({behavior:'auto',block:'start'});}
 function setReading(value){reading=value;document.body.classList.toggle('reading',reading);$('read-btn').textContent=reading?'Apresentar':'Modo leitura';$('read-btn').setAttribute('aria-pressed',String(reading));scale();show(current,false);if(reading)slides[current].scrollIntoView({block:'start'});}
 function modal(id){pauseTimers();$(id).showModal();}
 $('prev-btn').addEventListener('click',()=>show(current-1));$('next-btn').addEventListener('click',()=>show(current+1));$('read-btn').addEventListener('click',()=>setReading(!reading));
 $('index-btn').addEventListener('click',()=>modal('index-dialog'));
 $('notes-btn').addEventListener('click',()=>{const s=slides[current];$('notes-title').textContent='Slide '+(current+1)+' · '+s.dataset.title;$('notes-body').textContent=s.querySelector('template.notes').content.textContent;modal('notes-dialog');});
 $('help-btn').addEventListener('click',()=>modal('help-dialog'));$('print-btn').addEventListener('click',()=>{pauseTimers();window.print();});
 $('full-btn').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{modal('help-dialog');}});
 document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
 slides.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0')+' · '+s.dataset.title;b.addEventListener('click',()=>{$('index-dialog').close();show(i);});$('index-list').append(b);});
 document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const a=$(b.dataset.answer);a.hidden=!a.hidden;b.setAttribute('aria-expanded',String(!a.hidden));b.textContent=a.hidden?b.dataset.original:'Ocultar resposta';}));document.querySelectorAll('[data-answer]').forEach(b=>b.dataset.original=b.textContent);
 const sendFeedback={yes:['warn','Enviar não prova recebimento. O caso não mostra se todos leram e compreenderam a revisão.'],unknown:['ok','Isso: sabemos que houve envio. Leitura, compreensão e repasse ainda precisam ser verificados.'],no:['warn','Também não podemos afirmar isso. Não há confirmação de leitura, mas isso não prova que ninguém recebeu.']};
 $('q-send').querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{const [cls,txt]=sendFeedback[b.dataset.choice],out=$('q-send').querySelector('.feedback');out.className='feedback '+cls;out.textContent=txt;$('q-send').querySelectorAll('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
 const moments=[
 ['Aviso v1\nJ-02 · Quadra 1','Mural','Aviso v1 publicado às 8h.','Podem consultar o aviso.\nLeitura não observada.','R1: existe um aviso. Ainda não sabemos quem o consultou.'],
 ['Revisão às 9h\nJ-02 · Quadra 2','Registro de revisão','A nova localização foi registrada pela comissão.','Recebimento da revisão\nnão observado.','R2: a informação foi atualizada na origem. Isso não prova atualização em todos os canais.'],
 ['Revisão disponível\nJ-02 · Quadra 2','Mensagem enviada','Secretaria → representante, às 9h05.','Repasse aos demais\nnão observado.','R3: envio ao representante registrado; leitura e repasse não confirmados pelo material.'],
 ['Revisão às 9h\nJ-02 · Quadra 2','Mural às 9h15','Ainda mostra v1: J-02 na Quadra 1.','Qual versão cada equipe\nusou? Não sabemos.','R2 + R4: coexistem localizações diferentes. A causa e as consequências permanecem a investigar.']];
 function flow(k){const m=moments[k];['flow-origin','flow-medium-title','flow-medium','flow-dest','flow-caption'].forEach((id,i)=>{$(id).textContent=m[i];$(id).style.whiteSpace='pre-line';});document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.time)===k)));}
 document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>flow(Number(b.dataset.time))));
 const classKeys=['r','h','s'],classFeedback=['Registro do caso: R4 informa o estado do mural às 9h15.','Hipótese: o caso não informa quem recebeu a revisão para atualizar o mural.','Solução antecipada: propõe uma tecnologia antes de concluir a investigação.'];
 $('check-class').addEventListener('click',()=>{document.querySelectorAll('[data-class]').forEach((s,i)=>{const out=s.closest('article').querySelector('.result');out.className='result'+(s.value===classKeys[i]?'':' warn');out.textContent=!s.value?'Escolha uma classificação para conferir.':(s.value===classKeys[i]?'Correto. ':'Reveja. ')+classFeedback[i];});});
 const cases=JSON.parse($('cases-data').textContent);
 function showCase(k){const c=cases[k],root=$('case-content');root.replaceChildren();const h=document.createElement('h2');h.textContent=c.title;root.append(h);c.records.forEach(([id,text])=>{const p=document.createElement('p'),b=document.createElement('strong');b.textContent=id+' — ';p.append(b,document.createTextNode(text));root.append(p);});const limit=document.createElement('p');limit.className='case-source';limit.textContent='Limite: '+c.limit;root.append(limit);document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===k)));}
 document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>showCase(b.dataset.case)));showCase('memorias');
 document.querySelectorAll('.timer').forEach(el=>{let remaining=Number(el.dataset.seconds),handle=null,deadline=0;const clock=el.querySelector('.clock'),toggle=el.querySelector('.timer-toggle');function paint(){clock.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');}function pause(){if(handle!==null){remaining=Math.max(0,Math.ceil((deadline-performance.now())/1000));clearInterval(handle);handle=null;toggle.textContent=remaining>0?'Continuar':'Tempo encerrado';paint();}}function tick(){remaining=Math.max(0,Math.ceil((deadline-performance.now())/1000));paint();if(!remaining){pause();toggle.textContent='Tempo encerrado';}}function reset(){pause();remaining=Number(el.dataset.seconds);toggle.textContent='Iniciar';paint();}toggle.addEventListener('click',()=>{if(handle!==null){pause();return;}if(!remaining)return;deadline=performance.now()+remaining*1000;toggle.textContent='Pausar';handle=setInterval(tick,200);});el.querySelector('.timer-reset').addEventListener('click',reset);timers.push({el,pause,reset});paint();});
 let board=0;function setBoard(n,msg,cls='ok'){board=n;document.querySelectorAll('[data-state]').forEach(e=>e.classList.toggle('selected',Number(e.dataset.state)===board));$('board-message').textContent=msg;$('board-message').className='feedback '+cls;}
 $('board-start').addEventListener('click',()=>{if(board!==0){setBoard(board,'A tarefa já foi iniciada. Registre e confira antes de concluir.','warn');return;}setBoard(1,'T5 está em “Fazendo”. Produza e identifique a ficha F-01.');});
 $('board-review').addEventListener('click',()=>{if(board!==1){setBoard(board,'Primeiro inicie a tarefa. Só a etapa “Fazendo” pode seguir para conferência.','warn');return;}if(!$('has-evidence').checked){setBoard(board,'Falta evidência: identifique o registro produzido antes de pedir conferência.','warn');return;}setBoard(2,'T5 está em “Conferindo”. Peça a leitura e a revisão do registro.');});
 $('board-done').addEventListener('click',()=>{if(board!==2||!$('has-evidence').checked||!$('has-review').checked){setBoard(board,'Ainda não: concluir exige passar pela conferência, com registro identificado e revisão realizada.','warn');return;}setBoard(3,'T5 concluída: o registro do caso foi produzido e revisado. A lacuna do mundo real continua aberta.');});
 // Remover uma condição depois da conclusão reabre a demonstração.
 $('has-evidence').addEventListener('change',()=>{if(!$('has-evidence').checked&&board>=2)setBoard(1,'Sem registro identificado, a tarefa volta para “Fazendo”.','warn');});$('has-review').addEventListener('change',()=>{if(!$('has-review').checked&&board===3)setBoard(2,'Sem revisão concluída, a tarefa volta para “Conferindo”.','warn');});
 $('reset-btn').addEventListener('click',()=>{const s=slides[current];s.querySelectorAll('[data-answer]').forEach(b=>{$(b.dataset.answer).hidden=true;b.setAttribute('aria-expanded','false');b.textContent=b.dataset.original;});s.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);timers.filter(t=>s.contains(t.el)).forEach(t=>t.reset());if(current===2){const out=$('q-send').querySelector('.feedback');out.className='feedback';out.textContent='O que o enunciado realmente permite afirmar?';$('q-send').querySelectorAll('[data-choice]').forEach(b=>b.removeAttribute('aria-pressed'));}if(current===6)flow(0);if(current===8){s.querySelectorAll('select').forEach(x=>x.value='');s.querySelectorAll('.result').forEach(x=>x.textContent='');}if(current===12)showCase('memorias');if(current===17)setBoard(0,'T5 está em “A fazer”. Teste os critérios de passagem.','');});
 addEventListener('resize',scale);addEventListener('hashchange',()=>{const m=location.hash.match(/^#s(\d+)$/);if(m)show(Number(m[1])-1);});
 addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('input,textarea,select,button,a,[contenteditable="true"]'))return;if(e.altKey||e.ctrlKey||e.metaKey)return;const k=e.key.toLowerCase();if(!reading&&['arrowleft','arrowright','pageup','pagedown','home','end'].includes(k)){e.preventDefault();if(k==='home')show(0);else if(k==='end')show(slides.length-1);else show(current+(['arrowright','pagedown'].includes(k)?1:-1));}else if(k==='i')modal('index-dialog');});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseTimers();});addEventListener('beforeprint',pauseTimers);
 const hash=location.hash.match(/^#s(\d+)$/);if(hash)current=Math.min(slides.length-1,Math.max(0,Number(hash[1])-1));setReading(reading);scale();show(current,false);
 // Métodos sem efeitos externos para a checagem automatizada da interface.
 window.ppiLesson={show,flow,showCase,setReading,get current(){return current;},get count(){return slides.length;}};
})();
