
(()=>{'use strict';
 const slides=[...document.querySelectorAll('.slide')], $=id=>document.getElementById(id);
 let current=0,reading=innerWidth<800; const timers=[];
 function scale(){if(reading)return;const v=$('viewport'),bar=$('toolbar');v.style.bottom=(bar.offsetHeight+8)+'px';const scale=Math.min((v.clientWidth-16)/1280,(v.clientHeight-12)/720);document.documentElement.style.setProperty('--scale',String(Math.max(0.1,scale)));}
 function pauseTimers(){timers.forEach(t=>t.pause());}
 function show(index,scroll=true){current=Math.max(0,Math.min(slides.length-1,Number(index)||0));pauseTimers();slides.forEach((s,i)=>{s.classList.toggle('active',i===current);if(!reading)s.setAttribute('aria-hidden',String(i!==current));else s.removeAttribute('aria-hidden');});$('counter').textContent=String(current+1).padStart(2,'0')+' / '+slides.length;$('prev-btn').disabled=current===0;$('next-btn').disabled=current===slides.length-1;history.replaceState(null,'','#s'+String(current+1).padStart(2,'0'));if(reading&&scroll)slides[current].scrollIntoView({behavior:'auto',block:'start'});}
 function setReading(value){reading=value;document.body.classList.toggle('reading',reading);$('read-btn').textContent=reading?'Apresentar':'Modo leitura';$('read-btn').setAttribute('aria-pressed',String(reading));scale();show(current,false);if(reading)slides[current].scrollIntoView({block:'start'});}
 function modal(id){pauseTimers();$(id).showModal();}
 $('prev-btn').addEventListener('click',()=>show(current-1));$('next-btn').addEventListener('click',()=>show(current+1));$('read-btn').addEventListener('click',()=>setReading(!reading));
 $('index-btn').addEventListener('click',()=>modal('index-dialog'));
 $('notes-btn').addEventListener('click',()=>{const s=slides[current];$('notes-title').textContent='Slide '+(current+1)+' · '+s.dataset.title;$('notes-body').textContent=s.querySelector('template.notes').content.textContent;modal('notes-dialog');});
 $('help-btn').addEventListener('click',()=>modal('help-dialog'));$('print-btn').addEventListener('click',()=>{pauseTimers();window.print();});
 $('full-btn').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{modal('help-dialog');}});
 document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));
 slides.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0')+' · '+s.dataset.title;b.addEventListener('click',()=>{$('index-dialog').close();show(i);});$('index-list').append(b);});
 document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const a=$(b.dataset.answer);a.hidden=!a.hidden;b.setAttribute('aria-expanded',String(!a.hidden));b.textContent=a.hidden?b.dataset.original:'Ocultar resposta';}));document.querySelectorAll('[data-answer]').forEach(b=>b.dataset.original=b.textContent);
 const sendFeedback={yes:['warn','Enviar não prova que todos leram. O caso só informa que o aviso foi enviado.'],unknown:['ok','Isso! Sabemos que o aviso foi enviado. Ainda falta descobrir quem leu, entendeu e passou o recado.'],no:['warn','Também não sabemos disso. A falta de confirmação não prova que ninguém recebeu o aviso.']};
 $('q-send').querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{const [cls,txt]=sendFeedback[b.dataset.choice],out=$('q-send').querySelector('.feedback');out.className='feedback '+cls;out.textContent=txt;$('q-send').querySelectorAll('[data-choice]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
 const moments=[["Jogo às 14h\nQuadra 1", "Mural", "O primeiro aviso foi publicado às 8h.", "Podem consultar o mural.\nNão sabemos quem leu.", "O aviso existe. Isso ainda não prova que todos o leram."], ["Mudança às 9h\nJogo na Quadra 2", "Anotação da mudança", "A comissão registra o novo lugar do jogo.", "Não sabemos quem\nrecebeu a mudança.", "A comissão mudou a informação. Falta saber se os outros avisos também mudaram."], ["Novo lugar registrado\nQuadra 2", "Mensagem enviada", "Às 9h05, a secretaria envia o aviso ao representante.", "Não sabemos se houve\nleitura e repasse.", "A mensagem foi enviada. Enviar não é o mesmo que confirmar que todos leram."], ["Mudança registrada\nQuadra 2", "Mural às 9h15", "Ainda mostra o lugar antigo: Quadra 1.", "Qual aviso os participantes\nusaram? Não sabemos.", "O novo aviso diz Quadra 2. O mural ainda diz Quadra 1. Temos uma diferença para investigar."]];
 function flow(k){const m=moments[k];['flow-origin','flow-medium-title','flow-medium','flow-dest','flow-caption'].forEach((id,i)=>{$(id).textContent=m[i];$(id).style.whiteSpace='pre-line';});document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.time)===k)));}
 document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>flow(Number(b.dataset.time))));
 const classKeys=['r','h','s'],classFeedback=['Fato registrado: a anotação das 9h15 diz que o mural ainda mostrava a Quadra 1.','Hipótese: é uma explicação possível, mas não sabemos quem recebeu o novo aviso.','Solução proposta: criar um aplicativo. Antes de escolher a solução, precisamos entender o problema.'];
 $('check-class').addEventListener('click',()=>{document.querySelectorAll('[data-class]').forEach((s,i)=>{const out=s.closest('article').querySelector('.result');out.className='result'+(s.value===classKeys[i]?'':' warn');out.textContent=!s.value?'Escolha uma resposta antes de conferir.':(s.value===classKeys[i]?'Correto. ':'Reveja. ')+classFeedback[i];});});
 const cases=JSON.parse($('cases-data').textContent);
 function showCase(k){const c=cases[k],root=$('case-content');root.replaceChildren();const h=document.createElement('h2');h.textContent=c.title;root.append(h);c.records.forEach(([id,text])=>{const p=document.createElement('p'),b=document.createElement('strong');b.textContent=id+' — ';p.append(b,document.createTextNode(text));root.append(p);});const limit=document.createElement('p');limit.className='case-source';limit.textContent='O que ainda não sabemos: '+c.limit;root.append(limit);document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.case===k)));}
 document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>showCase(b.dataset.case)));showCase('memorias');
 document.querySelectorAll('.timer').forEach(el=>{let remaining=Number(el.dataset.seconds),handle=null,deadline=0;const clock=el.querySelector('.clock'),toggle=el.querySelector('.timer-toggle');function paint(){clock.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');}function pause(){if(handle!==null){remaining=Math.max(0,Math.ceil((deadline-performance.now())/1000));clearInterval(handle);handle=null;toggle.textContent=remaining>0?'Continuar':'Tempo encerrado';paint();}}function tick(){remaining=Math.max(0,Math.ceil((deadline-performance.now())/1000));paint();if(!remaining){pause();toggle.textContent='Tempo encerrado';}}function reset(){pause();remaining=Number(el.dataset.seconds);toggle.textContent='Iniciar';paint();}toggle.addEventListener('click',()=>{if(handle!==null){pause();return;}if(!remaining)return;deadline=performance.now()+remaining*1000;toggle.textContent='Pausar';handle=setInterval(tick,200);});el.querySelector('.timer-reset').addEventListener('click',reset);timers.push({el,pause,reset});paint();});
 let board=0;function setBoard(n,msg,cls='ok'){board=n;document.querySelectorAll('[data-state]').forEach(e=>e.classList.toggle('selected',Number(e.dataset.state)===board));$('board-message').textContent=msg;$('board-message').className='feedback '+cls;}
 $('board-start').addEventListener('click',()=>{if(board!==0){setBoard(board,'Você já iniciou. Preencha e guarde a ficha antes de pedir revisão.','warn');return;}setBoard(1,'A tarefa está em “Fazendo”. Preencha e guarde a ficha da equipe.');});
 $('board-review').addEventListener('click',()=>{if(board!==1){setBoard(board,'Primeiro clique em “Iniciar tarefa”. Depois preencha a ficha para pedir revisão.','warn');return;}if(!$('has-evidence').checked){setBoard(board,'A ficha ainda não está pronta. Preencha, guarde e marque a primeira caixa antes de pedir revisão.','warn');return;}setBoard(2,'A tarefa está em “Conferindo”. Outra equipe precisa ler e conferir a ficha.');});
 $('board-done').addEventListener('click',()=>{if(board!==2||!$('has-evidence').checked||!$('has-review').checked){setBoard(board,'Ainda não. Para concluir, a ficha precisa estar preenchida, guardada e conferida por outra equipe.','warn');return;}setBoard(3,'Ficha concluída e conferida! Isso não significa que a dúvida do projeto já foi respondida.');});
 // Remover uma condição depois da conclusão reabre a demonstração.
 $('has-evidence').addEventListener('change',()=>{if(!$('has-evidence').checked&&board>=2)setBoard(1,'Sem a ficha pronta e guardada, a tarefa volta para “Fazendo”.','warn');});$('has-review').addEventListener('change',()=>{if(!$('has-review').checked&&board===3)setBoard(2,'Sem a conferência de outra equipe, a tarefa volta para “Conferindo”.','warn');});
 $('reset-btn').addEventListener('click',()=>{const s=slides[current];s.querySelectorAll('[data-answer]').forEach(b=>{$(b.dataset.answer).hidden=true;b.setAttribute('aria-expanded','false');b.textContent=b.dataset.original;});s.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);timers.filter(t=>s.contains(t.el)).forEach(t=>t.reset());if(current===2){const out=$('q-send').querySelector('.feedback');out.className='feedback';out.textContent='O que a situação permite afirmar?';$('q-send').querySelectorAll('[data-choice]').forEach(b=>b.removeAttribute('aria-pressed'));}if(current===6)flow(0);if(current===8){s.querySelectorAll('select').forEach(x=>x.value='');s.querySelectorAll('.result').forEach(x=>x.textContent='');}if(current===12)showCase('memorias');if(current===17)setBoard(0,'A tarefa está em “A fazer”. Tente concluir antes de preencher e conferir.','');});
 addEventListener('resize',scale);if(window.visualViewport)window.visualViewport.addEventListener('resize',scale);addEventListener('hashchange',()=>{const m=location.hash.match(/^#s(\d+)$/);if(m)show(Number(m[1])-1);});
 addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('input,textarea,select,button,a,[contenteditable="true"]'))return;if(e.altKey||e.ctrlKey||e.metaKey)return;const k=e.key.toLowerCase();if(!reading&&['arrowleft','arrowright','pageup','pagedown','home','end'].includes(k)){e.preventDefault();if(k==='home')show(0);else if(k==='end')show(slides.length-1);else show(current+(['arrowright','pagedown'].includes(k)?1:-1));}else if(k==='i')modal('index-dialog');});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseTimers();});addEventListener('beforeprint',pauseTimers);
 const hash=location.hash.match(/^#s(\d+)$/);if(hash)current=Math.min(slides.length-1,Math.max(0,Number(hash[1])-1));setReading(reading);scale();show(current,false);flow(0);
 // Métodos sem efeitos externos para a checagem automatizada da interface.
 window.ppiLesson={show,flow,showCase,setReading,get current(){return current;},get count(){return slides.length;}};
})();
